# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_LENDER:      ROLE_LENDER
        ROLE_BORROWER:    ROLE_BORROWER
        ROLE_BROKER:      ROLE_BROKER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_LENDER, ROLE_BORROWER, ROLE_BROKER, ROLE_ADMIN,ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admin_area:
            pattern:    ^/admin
            http_basic: ~
            form_login:
                provider:     fos_userbundle
                login_path:   igniteyourproject_base_admin_bundle_login
                check_path:   igniteyourproject_base_admin_bundle_login_check
                failure_path: igniteyourproject_base_admin_bundle_login
                default_target_path: igniteyourproject_base_admin_bundle_dashboard
                use_forward:  false
                use_referer:  true
            logout:
                path:   igniteyourproject_base_admin_bundle_logout
                target: /
            anonymous: true
            switch_user: true
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
