<?php

namespace IgniteYourProject\Base\MovieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Movie
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Movie extends EntityRepository
{
    /**
     * Find the current active movies
     *
     * @return array
     */
    public function findAllAvailable()
    {
        return $this->_em
                ->createQuery(
                    'SELECT m
                    FROM IgniteYourProjectBaseMovieBundle:Movie m
                    WHERE m.available > 0'
                )->getResult();
    }
}
