<?php

namespace IgniteYourProject\Base\MovieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MovieRented
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRented extends EntityRepository
{
}
